services:
  - type: web
    name: zero2prod
    env: docker
    region: ohio
    plan: free
    branch: main
    envVars:
      - key: APP_APPLICATION__PORT
        sync: false
        value: ${PORT}
